
development:
  adapter: postgresql
  encoding: unicode
  database: pdfapp_development
  pool: 5
  host:     localhost
  username: pdfapp_admin
  password: Root@2020@#!*

test:
  adapter: postgresql
  encoding: unicode
  database: pdfapp_test
  pool: 5
  host:     localhost
  username: pdfapp_admin
  password: Root@2020@#!*

production:
  adapter: postgresql
  encoding: unicode
  database: pdfapp_production
  pool: 5
  host:     localhost
  username: pdfapp_admin
  password: Root@2020@#!*

staging:
  adapter: postgresql
  encoding: unicode
  database: pdfapp_staging
  pool: 5
  host:     localhost
  username: pdfapp_admin
  password: Root@2020@#!*
